repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args:
          - "--unsafe"
      - id: check-json
      - id: debug-statements
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - "--fix=lf"
      - id: no-commit-to-branch
        args:
          - "--branch"
          - main
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=4"
          - "--no-sort-keys"
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: mkdocs
        name: mkdocs build
        entry: bash -c "poetry run mkdocs build -cs --site-dir ./tmp/site && rm -Rf ./tmp/site" --
        language: system
        files: "^docs/.*\\.md$"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.290"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - "--check"
